"""
提示词模板包
"""
from .xhs_copywriting import SYSTEM_PROMPT, USER_PROMPT, DEFAULT_TONE_STYLE, DEFAULT_PRODUCT_NAME, DEFAULT_TARGET_AUDIENCE

__all__ = [
    "SYSTEM_PROMPT",
    "USER_PROMPT",
    "DEFAULT_TONE_STYLE",
    "DEFAULT_PRODUCT_NAME",
    "DEFAULT_TARGET_AUDIENCE",
]
